"""Exports the buddy sprites (buddies.py) to Core as Swift pixel data, plus the app icon.

Run from the repo root:  python3 scripts/buddies/export_swift.py
Needs Pillow only for the app icon. The Swift file is generated; edit buddies.py / face.py, not the
output. 48x48 pixels, eight faces per buddy (see face.EXPRS).
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import buddies
from engine import N

ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'Core/Sources/Core/UI/Buddy/BuddySprites.swift')
KEYS = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!#$%&()*+,-/:;<=>?@[]^_`{|}~'
ORDER = ['stash', 'zib', 'lox', 'pip', 'moko', 'brick', 'tank', 'volt', 'howl']
# Swift case name -> art expression. `idle` is the content face.
POSES = [('idle', 'content'), ('sleepy', 'sleepy'), ('happy', 'happy'), ('drained', 'drained'),
         ('sad', 'sad'), ('meh', 'meh'), ('excited', 'excited'), ('ecstatic', 'ecstatic')]

def encode(img):
    pal, rows = [], []
    for y in range(N):
        row = ''
        for x in range(N):
            c = img.get((x, y))
            if c is None:
                row += '.'
                continue
            if c not in pal:
                pal.append(c)
            row += KEYS[pal.index(c)]
        rows.append(row)
    assert len(pal) <= len(KEYS), len(pal)
    return pal, rows

def swift_string(row):
    return '"' + row.replace('\\', '\\\\').replace('"', '\\"') + '"'

out = ['// BuddySprites.swift', '// Core / UI / Buddy', '//',
       '// GENERATED by scripts/buddies/export_swift.py from scripts/buddies/buddies.py. Do not edit by',
       '// hand: change the art there and re-run the script. 48x48 pixels per pose; "." is transparent,',
       '// every other character indexes `palette` (0xRRGGBB) through `BuddyPixels.keys`.', '',
       'extension Buddy {', '    /// The pixel art for `pose`.', '    public func pixels(_ pose: BuddyPose) -> BuddyPixels {',
       '        switch (self, pose) {']
defs = []
for name in ORDER:
    fn = buddies.B[name.capitalize()]
    for case, expr in POSES:
        pal, rows = encode(fn(expr).render())
        ident = f'{name}{case[0].upper()}{case[1:]}'
        out.append(f'        case (.{name}, .{case}): BuddySpriteData.{ident}')
        p = ', '.join('0x%02X%02X%02X' % c for c in pal)
        r = ',\n            '.join(swift_string(row) for row in rows)
        defs.append(f'    static let {ident} = BuddyPixels(\n        palette: [{p}],\n        rows: [\n            {r},\n        ]\n    )')
out += ['        }', '    }', '}', '', 'enum BuddySpriteData {']
out.append('\n\n'.join(defs))
out += ['}', '']
open(OUT, 'w').write('\n'.join(out))
print('wrote', os.path.relpath(OUT, ROOT))
print('keys:', KEYS)

# App icon: the default buddy (Stash), beaming, on the ink canvas with a soft teal glow.
try:
    from PIL import Image, ImageDraw, ImageFilter
except ImportError:
    sys.exit(0)
S = 1024
glow = Image.new('RGB', (S, S), (11, 14, 36))
ImageDraw.Draw(glow).ellipse((170, 190, 854, 874), fill=(26, 88, 92))
icon = glow.filter(ImageFilter.GaussianBlur(130))
img = buddies.B['Stash']('happy').render()
cell = 18
ox = (S - N * cell) // 2
oy = (S - N * cell) // 2 + 10
d = ImageDraw.Draw(icon)
for (x, y), c in img.items():
    d.rectangle((ox + x * cell, oy + y * cell, ox + (x + 1) * cell - 1, oy + (y + 1) * cell - 1), fill=c)
ICON = os.path.join(ROOT, 'App/ZANO/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png')
icon.save(ICON)
print('wrote', os.path.relpath(ICON, ROOT))
