"""Exports the buddy sprites (chars.py) to Core as Swift pixel data, plus the app icon.

Run from the repo root:  python3 scripts/buddies/export_swift.py
Needs Pillow only for the app icon. The Swift file is generated; edit chars.py, not the output.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import chars
from eng import N
# Sleep "z"s and sparkles are drawn by the app's motion layer, not baked into the sprite.
chars.zzz = lambda s: None
# (The sweat drop on `tired` is part of the face, so it stays.)
chars.spark = lambda s, c=None: None

ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'Core/Sources/Core/UI/Buddy/BuddySprites.swift')
KEYS = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
ORDER = ['stash', 'zib', 'lox', 'pip', 'moko', 'brick', 'tank', 'volt', 'howl']
POSES = ['idle', 'sleepy', 'happy', 'tired', 'meh', 'grin']

def encode(img):
    pal = []
    rows = []
    for y in range(N):
        row = ''
        for x in range(N):
            c = img.get((x, y))
            if c is None:
                row += '.'
                continue
            if c not in pal:
                pal.append(c)
            row += KEYS[pal.index(c)]
        rows.append(row)
    assert len(pal) <= len(KEYS), len(pal)
    return pal, rows

out = ['// BuddySprites.swift', '// Core / UI / Buddy', '//',
       '// GENERATED by scripts/buddies/export_swift.py from scripts/buddies/chars.py. Do not edit by hand:',
       '// change the art there and re-run the script. 32x32 pixels per pose; "." is transparent, every',
       '// other character indexes `palette` (0xRRGGBB).', '',
       'extension Buddy {', '    /// The pixel art for `pose`.', '    public func pixels(_ pose: BuddyPose) -> BuddyPixels {',
       '        switch (self, pose) {']
defs = []
for name in ORDER:
    fn = chars.CHARS[name.capitalize()]
    for pose in POSES:
        pal, rows = encode(fn(pose).render())
        ident = f'{name}{pose.capitalize()}'
        out.append(f'        case (.{name}, .{pose}): BuddySpriteData.{ident}')
        p = ', '.join('0x%02X%02X%02X' % c for c in pal)
        r = ',\n            '.join(f'"{row}"' for row in rows)
        defs.append(f'    static let {ident} = BuddyPixels(\n        palette: [{p}],\n        rows: [\n            {r},\n        ]\n    )')
out += ['        }', '    }', '}', '', 'enum BuddySpriteData {']
out.append('\n\n'.join(defs))
out += ['}', '']
open(OUT, 'w').write('\n'.join(out))
print('wrote', os.path.relpath(OUT, ROOT))

# App icon: the default buddy (Stash) on the ink canvas with a soft accent glow.
try:
    from PIL import Image, ImageDraw, ImageFilter
except ImportError:
    sys.exit(0)
S = 1024
icon = Image.new('RGB', (S, S), (11, 14, 36))
glow = Image.new('RGB', (S, S), (11, 14, 36))
ImageDraw.Draw(glow).ellipse((150, 170, 874, 894), fill=(28, 92, 96))
icon = Image.blend(icon, glow.filter(ImageFilter.GaussianBlur(120)), 1.0)
img = chars.CHARS['Stash']('idle').render()
cell = 24
ox = (S - N * cell) // 2
oy = (S - N * cell) // 2 + 20
d = ImageDraw.Draw(icon)
for (x, y), c in img.items():
    d.rectangle((ox + x * cell, oy + y * cell, ox + (x + 1) * cell - 1, oy + (y + 1) * cell - 1), fill=c)
ICON = os.path.join(ROOT, 'App/ZANO/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png')
icon.save(ICON)
print('wrote', os.path.relpath(ICON, ROOT))
