"""Exports the buddy sprites (buddies.py) to Core as Swift pixel data, plus the app icon.

Run from the repo root:  python3 scripts/buddies/export_swift.py
Needs Pillow only for the app icon. The Swift file is generated; edit buddies.py / face.py, not the
output. 48x48 pixels, eight faces per buddy (see face.EXPRS).
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import buddies
from engine import N

ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'Core/Sources/Core/UI/Buddy/BuddySprites.swift')
KEYS = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!#$%&()*+,-/:;<=>?@[]^_`{|}~'
ORDER = ['stash', 'zib', 'lox', 'pip', 'moko', 'brick', 'tank', 'volt', 'howl']
# Swift case name -> art expression. `idle` is the content face.
POSES = [('idle', 'content'), ('sleepy', 'sleepy'), ('happy', 'happy'), ('drained', 'drained'),
         ('sad', 'sad'), ('meh', 'meh'), ('excited', 'excited'), ('ecstatic', 'ecstatic')]

def encode(img):
    pal, rows = [], []
    for y in range(N):
        row = ''
        for x in range(N):
            c = img.get((x, y))
            if c is None:
                row += '.'
                continue
            if c not in pal:
                pal.append(c)
            row += KEYS[pal.index(c)]
        rows.append(row)
    assert len(pal) <= len(KEYS), len(pal)
    return pal, rows

def swift_string(row):
    return '"' + row.replace('\\', '\\\\').replace('"', '\\"') + '"'

out = ['// BuddySprites.swift', '// Core / UI / Buddy', '//',
       '// GENERATED by scripts/buddies/export_swift.py from scripts/buddies/buddies.py. Do not edit by',
       '// hand: change the art there and re-run the script. 48x48 pixels per pose; "." is transparent,',
       '// every other character indexes `palette` (0xRRGGBB) through `BuddyPixels.keys`.', '',
       'extension Buddy {', '    /// The pixel art for `pose`.', '    public func pixels(_ pose: BuddyPose) -> BuddyPixels {',
       '        switch (self, pose) {']
defs = []
for name in ORDER:
    fn = buddies.B[name.capitalize()]
    for case, expr in POSES:
        pal, rows = encode(fn(expr).render())
        ident = f'{name}{case[0].upper()}{case[1:]}'
        out.append(f'        case (.{name}, .{case}): BuddySpriteData.{ident}')
        p = ', '.join('0x%02X%02X%02X' % c for c in pal)
        r = ',\n            '.join(swift_string(row) for row in rows)
        defs.append(f'    static let {ident} = BuddyPixels(\n        palette: [{p}],\n        rows: [\n            {r},\n        ]\n    )')
out += ['        }', '    }', '}', '', 'enum BuddySpriteData {']
out.append('\n\n'.join(defs))
out += ['}', '']
open(OUT, 'w').write('\n'.join(out))
print('wrote', os.path.relpath(OUT, ROOT))
print('keys:', KEYS)

# App icons: one per buddy, each beaming on the ink canvas over a soft glow in its signature colour.
# Stash (the default) is the primary `AppIcon`; the others are alternate icons `AppIcon-<Name>`
# (listed in project.yml's ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES), switched by the app when
# the user teams up with a buddy.
try:
    from PIL import Image, ImageDraw, ImageFilter
except ImportError:
    sys.exit(0)
import json
SIGNATURE = {'stash': (43, 181, 160), 'zib': (63, 123, 255), 'lox': (255, 138, 61), 'pip': (143, 91, 255),
             'moko': (47, 184, 107), 'brick': (229, 72, 77), 'tank': (200, 240, 74), 'volt': (31, 162, 255),
             'howl': (91, 123, 255)}
ASSETS = os.path.join(ROOT, 'App/ZANO/Assets.xcassets')

def icon_for(name):
    S = 1024
    ink = (11, 14, 36)
    glow = Image.new('RGB', (S, S), ink)
    sig = SIGNATURE[name]
    tint = tuple(round(ink[i] * 0.55 + sig[i] * 0.45) for i in range(3))
    ImageDraw.Draw(glow).ellipse((170, 190, 854, 874), fill=tint)
    icon = glow.filter(ImageFilter.GaussianBlur(130))
    img = buddies.B[name.capitalize()]('happy').render()
    cell = 18
    ox = (S - N * cell) // 2
    oy = (S - N * cell) // 2 + 10
    d = ImageDraw.Draw(icon)
    for (x, y), c in img.items():
        d.rectangle((ox + x * cell, oy + y * cell, ox + (x + 1) * cell - 1, oy + (y + 1) * cell - 1), fill=c)
    return icon

for name in ORDER:
    folder = 'AppIcon' if name == 'stash' else f'AppIcon-{name.capitalize()}'
    path = os.path.join(ASSETS, f'{folder}.appiconset')
    os.makedirs(path, exist_ok=True)
    icon_for(name).save(os.path.join(path, 'AppIcon-1024.png'))
    json.dump({'images': [{'filename': 'AppIcon-1024.png', 'idiom': 'universal', 'platform': 'ios', 'size': '1024x1024'}],
               'info': {'author': 'xcode', 'version': 1}}, open(os.path.join(path, 'Contents.json'), 'w'), indent=2)
    print('wrote', os.path.relpath(path, ROOT))
