// BuddyAppIcon.swift
// App / ZANO / Features / Buddy
//
// The Home Screen icon is the user's buddy (2026-10-03). Stash is the primary icon (`AppIcon`); the
// other eight are alternate icon sets `AppIcon-<Name>` (generated by scripts/buddies/export_swift.py,
// registered in project.yml). Applied when the user teams up with a buddy (picker's button), not
// on every tile tap: iOS shows its own "You have changed the icon" alert on each switch, so one
// switch per decision. Skipped in screenshot runs and when the icon already matches.

import UIKit
import Core

enum BuddyAppIcon {
    /// The alternate icon name for `buddy`, or nil for the primary icon (Stash).
    static func iconName(for buddy: Buddy) -> String? {
        buddy == .default ? nil : "AppIcon-\(buddy.rawValue.capitalized)"
    }

    @MainActor
    static func apply(_ buddy: Buddy) {
        guard ScreenshotMode.screen == nil else { return }
        let app = UIApplication.shared
        guard app.supportsAlternateIcons else { return }
        let name = iconName(for: buddy)
        guard app.alternateIconName != name else { return }
        // The async form: a completion closure declared here would be main-actor isolated, and
        // UIKit may call it off the main thread (a Swift 6 runtime trap).
        Task { try? await app.setAlternateIconName(name) }
    }
}
